server:
  port: 10100
spring:
  application:
    name: mock-a
  # Springboot2.6后 SpringMVC 处理映射匹配的默认策略已从AntPathMatcher变为PathPatternParser。
  # 修改配置否则swagger启动报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# 调用服务
grpc:
  client:
    # gRPC的服务端名单 @GrpcClient 注解中会用到
    mygrpc-server:
      address: 'static://localhost:10204'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
mock:
  call:
    nettyHost: 127.0.0.1
    nettyPort: 10202
    vertxHost: 127.0.0.1
    vertxPort: 10203
    grpcHost: 127.0.0.1
    grpcPort: 10204
# 提供服务
svc:
  network:
    httpHost: 127.0.0.1
    httpPort: 10101
    nettyHost: 127.0.0.1
    nettyPort: 10102
    vertxHost: 127.0.0.1
    vertxPort: 10103
    grpcHost: 127.0.0.1
    grpcPort: 10104