server:
  port: 10200
spring:
  application:
    name: mock-b
# 调用服务
mock:
  call:
    nettyHost: 127.0.0.1
    nettyPort: 10302
    vertxHost: 127.0.0.1
    vertxPort: 10303
    grpcHost: 127.0.0.1
    grpcPort: 10304
# 提供服务
svc:
  network:
    httpHost: 127.0.0.1
    httpPort: 10201
    nettyHost: 127.0.0.1
    nettyPort: 10202
    vertxHost: 127.0.0.1
    vertxPort: 10203
    grpcHost: 127.0.0.1
    grpcPort: 10204